name: Pull Request Developer Metrics
on:
  workflow_call:

jobs:
  Develpoer_Metrics:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The name of the branch is ${{ github.ref }}"
      - uses: actions/checkout@v2
      - run: |
          echo "Hey Shakti, How are you?"
          echo "The of the repository is : ${{ github.repository }}"
          echo "The name of the branch is : ${{ github.title }}"
        env:
          API_KEY: ${{ secrets.API_TOKEN_GITHUB }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

