name: Pull Request Stats

on: pull_request

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build Version - ${{ jobs.build.output.version }}"
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@v2.3.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repositories: ${{ github.repository }}
          period: 30
          charts: true
          disable-links: true
          sort-by: 'COMMENTS'
