name: Run API Automation Scripts

on:
#  pull_request:
  workflow_dispatch:
    branches:
      - master
jobs:
  job1:
    name: API_Automation_Scripts
    runs-on: ubuntu-latest
    steps:
      - run: echo "The name of the branch is ${{ github.ref }}"
      - uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: |
          python3 -m pip install pipenv
          python3 -m pipenv shell
          python3 -m pipenv install
          python3 -m pipenv run robot -d OutputFiles TestCases/Reqres_API_Tests.robot
        env:
          API_KEY: ${{ secrets.API_TOKEN_GITHUB }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
